# Generated by Django 5.2.7 on 2025-10-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('png', 'Image'), ('jpg', 'Image'), ('jpeg', 'Image'), ('txt', 'Text')], max_length=10),
        ),
    ]
